[build]
  publish = "dist-netlify/"
  command = "npm run netlify"

[[redirects]]
  from = "/data-viewer/*"
  to = "/data-viewer/404.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/data-viewer/"
  status = 302
